apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-san-eco-svm2
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san-economy"
  storagePools: "svm2-san-eco:aggr1_cluster3_02"
  fsType: "ext4"
mountOptions:
   - discard
allowVolumeExpansion: true