---
apiVersion: v1
kind: Namespace
metadata:
  name: sc06busybox
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydata
  namespace: sc06busybox
  labels:
    app.kubernetes.io/name: scenario06
    app: busybox
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-nas-svm2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: sc06busybox
  labels:
    app.kubernetes.io/name: scenario06
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scenario06
      app: busybox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scenario06
        app: busybox
    spec:
      containers:
      - name: busybox
        image: registry.demo.netapp.com/busybox:1.35.0
        imagePullPolicy: IfNotPresent
        command: ['sleep', '3600']        
        volumeMounts:
        - mountPath: /data
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: mydata
