apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mydata-snapshot
  namespace: sc06busybox
  labels:
    app.kubernetes.io/name: scenario06
    app: busybox
spec:
  volumeSnapshotClassName: csi-snapclass
  source:
    persistentVolumeClaimName: mydata