apiVersion: astra.netapp.io/v1
kind: Schedule
metadata:
  name: sched
  namespace: astra-connector
spec:
  applicationRef: wpargo
  appVaultRef: rke2-appvault
  backupRetention: "2"
  snapshotRetention: "1"
  granularity: hourly
  minute: "10"