apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-protect
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://192.168.0.203:30000/lod/scenario07'
    path: Astra
    targetRevision: master
    directory:
      recurse: true
      exclude: schedule.yaml
  destination:
    server: 'https://api.rke2.demo.netapp.com:6443'
    namespace: astra-connector
  syncPolicy:
    automated: {}
    syncOptions:
      - ApplyOutOfSyncOnly=true