apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-san-svm1
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
  fsType: "ext4"
mountOptions:
   - discard
allowVolumeExpansion: true