apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-ontap-nas-eco
  namespace: trident
spec:
  version: 1
  backendName: svm1-nas-eco
  storageDriverName: ontap-nas-economy
  managementLIF: 192.168.0.133
  storagePrefix: naseco_
  defaults:
    snapshotDir: 'true' 
  credentials:
    name: ontap-svm1-secret